module Evergreen.Migrate.V71 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocSet
import Evergreen.V69.CreateGroupPage
import Evergreen.V69.Group
import Evergreen.V69.GroupPage
import Evergreen.V69.ProfilePage
import Evergreen.V69.TimeZone
import Evergreen.V69.Types
import Evergreen.V71.CreateGroupPage
import Evergreen.V71.Group
import Evergreen.V71.GroupPage
import Evergreen.V71.ProfilePage
import Evergreen.V71.TimeZone
import Evergreen.V71.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V69.Types.FrontendModel -> ModelMigration Evergreen.V71.Types.FrontendModel Evergreen.V71.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V69.Types.BackendModel -> ModelMigration Evergreen.V71.Types.BackendModel Evergreen.V71.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V69.Types.FrontendMsg -> MsgMigration Evergreen.V71.Types.FrontendMsg Evergreen.V71.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V69.Types.ToBackend -> MsgMigration Evergreen.V71.Types.ToBackend Evergreen.V71.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V69.Types.BackendMsg -> MsgMigration Evergreen.V71.Types.BackendMsg Evergreen.V71.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V69.Types.ToFrontend -> MsgMigration Evergreen.V71.Types.ToFrontend Evergreen.V71.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
